/**
 * The TypeScript port of the matchup rule, checked against the same golden
 * fixture the Python tests use — pipeline/tests/golden/edges_2025.json, which
 * was generated by re-running the original main.py algorithm over the 2025
 * season. One fixture, two implementations, no drift.
 *
 *   npm test
 */

import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import type { Stats } from '../../api/schemas';
import { findEdges, summarize } from '../mismatch';
import { STATS, STAT_ORDER } from '../stats';

const ROOT = join(import.meta.dirname, '..', '..', '..', '..');
const GOLDEN = JSON.parse(
  readFileSync(join(ROOT, 'pipeline', 'tests', 'golden', 'edges_2025.json'), 'utf8'),
) as {
  pairs: Record<
    string,
    Array<{
      stat: string;
      mirror: string;
      team1_rank: number;
      team2_rank: number;
      team1_value: number;
      team2_value: number;
    }>
  >;
};

/** Rebuild a Stats payload from the archived 2025 CSVs. */
function loadStats(): Stats {
  const dir = join(ROOT, 'pipeline', 'tests', 'fixtures', 'csv2025');
  const trNameToId = new Map(
    Object.values(
      JSON.parse(
        readFileSync(join(ROOT, 'pipeline', 'props', 'data', 'teams.json'), 'utf8'),
      ).teams as Array<{ id: string; teamrankings: { name: string } }>,
    ).map((team) => [team.teamrankings.name, team.id] as const),
  );

  const stats: Stats['stats'] = [];
  for (const statId of STAT_ORDER) {
    const def = STATS[statId];
    const text = readFileSync(join(dir, `${def.label}.csv`), 'utf8');
    const lines = text.trim().split('\n');
    const header = lines[0].split(',');
    const teams: Stats['stats'][number]['teams'] = {};

    for (const line of lines.slice(1)) {
      const cells = line.split(',');
      const id = trNameToId.get(cells[2]);
      assert.ok(id, `unmapped team name ${cells[2]}`);
      teams[id] = {
        rank: Number(cells[1]),
        tied: false,
        pct: 0,
        season: num(cells[3]),
        last3: num(cells[4]),
        last1: num(cells[5]),
        home: num(cells[6]),
        away: num(cells[7]),
        prev_season: num(cells[8]),
        prev_rank: null,
      };
    }

    stats.push({
      id: def.id,
      label: def.label,
      short: def.short,
      unit: def.unit,
      phrase: def.phrase,
      mirror: def.mirror,
      higher_is_better: def.higherIsBetter,
      max_rank: Math.max(...Object.values(teams).map((t) => t.rank)),
      teams,
    });
  }

  return {
    season: Number(header_season(join(dir, 'Points Per Game.csv'))),
    prev_season: 2024,
    generated_at: new Date().toISOString(),
    stats,
  };
}

function header_season(path: string): string {
  return readFileSync(path, 'utf8').split('\n')[0].split(',')[3];
}

function num(value: string): number | null {
  const trimmed = (value ?? '').trim();
  if (trimmed === '--' || trimmed === '') return null;
  return Number(trimmed);
}

// ---------------------------------------------------------------------------

let checked = 0;
let failures = 0;

const stats = loadStats();
const labelToId = new Map(Object.values(STATS).map((s) => [s.label, s.id] as const));

for (const [pair, expected] of Object.entries(GOLDEN.pairs)) {
  const [team1, team2] = pair.split('_');
  const actual = findEdges(stats, team1, team2);
  checked += 1;

  try {
    assert.equal(actual.length, expected.length, `${pair}: edge count`);
    expected.forEach((want, index) => {
      const got = actual[index];
      assert.equal(got.statId, labelToId.get(want.stat), `${pair}[${index}] stat`);
      assert.equal(got.mirrorId, labelToId.get(want.mirror), `${pair}[${index}] mirror`);
      assert.equal(got.team1Rank, want.team1_rank, `${pair}[${index}] team1 rank`);
      assert.equal(got.team2Rank, want.team2_rank, `${pair}[${index}] team2 rank`);
      assert.equal(got.team1Value, want.team1_value, `${pair}[${index}] team1 value`);
      assert.equal(got.team2Value, want.team2_value, `${pair}[${index}] team2 value`);
    });
  } catch (error) {
    failures += 1;
    if (failures <= 5) console.error(String(error));
  }
}

// A few invariants beyond raw parity.
const sample = findEdges(stats, 'KC', 'DAL');
for (const edge of sample) {
  if (edge.advantage === 'KC') {
    assert.ok(edge.team1Rank <= 10 && edge.team2Rank > 20, 'advantage points the wrong way');
  } else {
    assert.ok(edge.team2Rank <= 10 && edge.team1Rank > 20, 'advantage points the wrong way');
  }
}
const counts = summarize(sample, 'KC', 'DAL');
assert.equal(counts.KC + counts.DAL, sample.length, 'summary must account for every edge');

const wideOpen = findEdges(stats, 'BUF', 'MIA', 32, 0);
assert.equal(wideOpen.length, 20, 'all 20 stats should fire with open thresholds');

console.log(`mismatch parity: ${checked - failures}/${checked} pairs matched the Python golden file`);
if (failures) {
  console.error(`${failures} pair(s) differ`);
  process.exit(1);
}
