"""The port must reproduce the original algorithm exactly.

edges_2025.json is generated by tools/legacy_parity.py, which reimplements the
old main.py loop from scratch. If these pass, find_edges() is behaviourally
identical to the CLI that has been in use for two seasons.
"""

from __future__ import annotations

import json
import pathlib

import pytest

from props.config import BY_LABEL, STATS, STAT_ORDER, mirror
from props.mismatch import find_edges, summarize
from props.transform.stats import from_csv_dir

HERE = pathlib.Path(__file__).resolve().parent
GOLDEN = json.loads((HERE / "golden" / "edges_2025.json").read_text())


@pytest.fixture(scope="module")
def stats():
    return from_csv_dir(HERE / "fixtures" / "csv2025")


def test_fixture_loads_a_full_season(stats):
    assert stats.season == 2025
    assert len(stats.tables) == 20
    for stat_id in STAT_ORDER:
        assert len(stats.stat(stat_id).teams) == 32


@pytest.mark.parametrize("pair", sorted(GOLDEN["pairs"]))
def test_matches_legacy_algorithm(stats, pair):
    team1, team2 = pair.split("_")
    expected = GOLDEN["pairs"][pair]
    actual = find_edges(stats, team1, team2)

    assert len(actual) == len(expected), f"{pair}: edge count differs"
    for got, want in zip(actual, expected):
        assert got.stat_id == BY_LABEL[want["stat"]]
        assert got.mirror_id == BY_LABEL[want["mirror"]]
        assert got.team1_rank == want["team1_rank"]
        assert got.team2_rank == want["team2_rank"]
        assert got.team1_value == pytest.approx(want["team1_value"])
        assert got.team2_value == pytest.approx(want["team2_value"])


def test_edges_are_emitted_in_stat_order(stats):
    edges = find_edges(stats, "BUF", "MIA")
    positions = [STAT_ORDER.index(e.stat_id) for e in edges]
    assert positions == sorted(positions)


def test_offense_and_defense_iterations_are_both_kept(stats):
    """The two directions of a stat pair are different matchups, not duplicates.

    Iterating "Passing Yards Per Game" reads team1's passing offense against
    team2's pass defense; iterating the mirror reads team1's pass defense
    against team2's passing offense. Deduplicating them would delete half the
    analysis, so this pins the behaviour down.
    """
    edges = find_edges(stats, "BUF", "MIA", elite=32, weak=0)
    assert len(edges) == 20, "all 20 stats should fire when thresholds are wide open"
    assert len({e.stat_id for e in edges}) == 20

    by_stat = {e.stat_id: e for e in edges}
    forward = by_stat["passing_yards_per_game"]
    backward = by_stat["opponent_passing_yards_per_game"]

    # Each side reads its own unit's rank from the underlying tables.
    assert forward.team1_rank == stats.value("passing_yards_per_game", "BUF").rank
    assert backward.team1_rank == stats.value(
        "opponent_passing_yards_per_game", "BUF"
    ).rank
    assert forward.team2_rank == stats.value(
        "opponent_passing_yards_per_game", "MIA"
    ).rank
    assert backward.team2_rank == stats.value("passing_yards_per_game", "MIA").rank

    # ...and those are four distinct readings, not one pair repeated.
    assert (forward.team1_rank, forward.team2_rank) != (
        backward.team1_rank,
        backward.team2_rank,
    )


def test_advantage_points_at_the_top_ten_side(stats):
    for pair in list(GOLDEN["pairs"])[:100]:
        team1, team2 = pair.split("_")
        for edge in find_edges(stats, team1, team2):
            if edge.advantage == team1:
                assert edge.team1_rank <= 10 and edge.team2_rank > 20
            else:
                assert edge.team2_rank <= 10 and edge.team1_rank > 20


def test_summary_counts_add_up(stats):
    edges = find_edges(stats, "PHI", "DAL")
    counts = summarize(edges, "PHI", "DAL")
    assert counts["PHI"] + counts["DAL"] == len(edges)


def test_thresholds_are_adjustable(stats):
    strict = find_edges(stats, "BUF", "MIA", elite=3, weak=29)
    default = find_edges(stats, "BUF", "MIA")
    assert len(strict) <= len(default)


def test_unknown_team_raises_instead_of_keyerror(stats):
    from props.models import MissingStatError

    with pytest.raises(MissingStatError):
        find_edges(stats, "BUF", "XXX")


def test_same_team_rejected(stats):
    with pytest.raises(ValueError):
        find_edges(stats, "BUF", "BUF")


def test_headline_reads_as_a_sentence(stats):
    edges = find_edges(stats, "KC", "DAL")
    if edges:
        assert " vs " in edges[0].headline
        assert edges[0].headline.startswith("Kansas City ")


def test_mirror_map_is_an_involution():
    for stat_id in STATS:
        assert mirror(mirror(stat_id)) == stat_id
