// Generated by `python -m props codegen`. Do not edit by hand.
// Source of truth: pipeline/props/{teams.py,config.py,markets.py}

export interface MarketDef {
  id: string;
  label: string;
  position: string;
  unit: string;
  noun: string;
}

export const MARKETS: Record<string, MarketDef> = {
  "wr_receiving_yards": {
    "id": "wr_receiving_yards",
    "label": "Receiving Yards",
    "position": "WR",
    "unit": "yds",
    "noun": "receiving yards"
  },
  "wr_receptions": {
    "id": "wr_receptions",
    "label": "Receptions",
    "position": "WR",
    "unit": "rec",
    "noun": "receptions"
  },
  "te_receiving_yards": {
    "id": "te_receiving_yards",
    "label": "Receiving Yards",
    "position": "TE",
    "unit": "yds",
    "noun": "receiving yards"
  },
  "te_receptions": {
    "id": "te_receptions",
    "label": "Receptions",
    "position": "TE",
    "unit": "rec",
    "noun": "receptions"
  },
  "rb_receiving_yards": {
    "id": "rb_receiving_yards",
    "label": "Receiving Yards",
    "position": "RB",
    "unit": "yds",
    "noun": "receiving yards"
  },
  "rb_receptions": {
    "id": "rb_receptions",
    "label": "Receptions",
    "position": "RB",
    "unit": "rec",
    "noun": "receptions"
  },
  "rb_rushing_yards": {
    "id": "rb_rushing_yards",
    "label": "Rushing Yards",
    "position": "RB",
    "unit": "yds",
    "noun": "rushing yards"
  },
  "rb_carries": {
    "id": "rb_carries",
    "label": "Carries",
    "position": "RB",
    "unit": "att",
    "noun": "carries"
  },
  "qb_rushing_yards": {
    "id": "qb_rushing_yards",
    "label": "Rushing Yards",
    "position": "QB",
    "unit": "yds",
    "noun": "rushing yards"
  },
  "qb_passing_yards": {
    "id": "qb_passing_yards",
    "label": "Passing Yards",
    "position": "QB",
    "unit": "yds",
    "noun": "passing yards"
  },
  "qb_passing_tds": {
    "id": "qb_passing_tds",
    "label": "Passing TDs",
    "position": "QB",
    "unit": "TD",
    "noun": "passing touchdowns"
  },
  "rb_anytime_td": {
    "id": "rb_anytime_td",
    "label": "Anytime TD",
    "position": "RB",
    "unit": "TD",
    "noun": "touchdowns"
  },
  "wr_anytime_td": {
    "id": "wr_anytime_td",
    "label": "Anytime TD",
    "position": "WR",
    "unit": "TD",
    "noun": "touchdowns"
  },
  "te_anytime_td": {
    "id": "te_anytime_td",
    "label": "Anytime TD",
    "position": "TE",
    "unit": "TD",
    "noun": "touchdowns"
  }
};

export const MARKET_ORDER: string[] = [
  "wr_receiving_yards",
  "wr_receptions",
  "te_receiving_yards",
  "te_receptions",
  "rb_receiving_yards",
  "rb_receptions",
  "rb_rushing_yards",
  "rb_carries",
  "qb_rushing_yards",
  "qb_passing_yards",
  "qb_passing_tds",
  "rb_anytime_td",
  "wr_anytime_td",
  "te_anytime_td"
];

export const POSITIONS = ['QB', 'RB', 'WR', 'TE'] as const;
