// Generated by `python -m props codegen`. Do not edit by hand.
// Source of truth: pipeline/props/{teams.py,config.py,markets.py}

export interface StatDef {
  id: string;
  label: string;
  short: string;
  unit: 'offense' | 'defense' | 'special';
  phrase: string;
  mirror: string;
  higherIsBetter: boolean;
}

export const STATS: Record<string, StatDef> = {
  "passing_yards_per_game": {
    "id": "passing_yards_per_game",
    "label": "Passing Yards Per Game",
    "short": "Pass Yds/G",
    "unit": "offense",
    "phrase": "passing offense",
    "mirror": "opponent_passing_yards_per_game",
    "higherIsBetter": true
  },
  "opponent_passing_yards_per_game": {
    "id": "opponent_passing_yards_per_game",
    "label": "Opponent Passing Yards Per Game",
    "short": "Opp Pass Yds/G",
    "unit": "defense",
    "phrase": "pass defense",
    "mirror": "passing_yards_per_game",
    "higherIsBetter": false
  },
  "passing_tds_per_game": {
    "id": "passing_tds_per_game",
    "label": "Passing TDs Per Game",
    "short": "Pass TD/G",
    "unit": "offense",
    "phrase": "passing offense",
    "mirror": "opponent_passing_tds_per_game",
    "higherIsBetter": true
  },
  "opponent_passing_tds_per_game": {
    "id": "opponent_passing_tds_per_game",
    "label": "Opponent Passing TDs Per Game",
    "short": "Opp Pass TD/G",
    "unit": "defense",
    "phrase": "pass defense",
    "mirror": "passing_tds_per_game",
    "higherIsBetter": false
  },
  "rushing_yards_per_game": {
    "id": "rushing_yards_per_game",
    "label": "Rushing Yards Per Game",
    "short": "Rush Yds/G",
    "unit": "offense",
    "phrase": "rushing offense",
    "mirror": "opponent_rushing_yards_per_game",
    "higherIsBetter": true
  },
  "opponent_rushing_yards_per_game": {
    "id": "opponent_rushing_yards_per_game",
    "label": "Opponent Rushing Yards Per Game",
    "short": "Opp Rush Yds/G",
    "unit": "defense",
    "phrase": "run defense",
    "mirror": "rushing_yards_per_game",
    "higherIsBetter": false
  },
  "rushing_tds_per_game": {
    "id": "rushing_tds_per_game",
    "label": "Rushing TDs Per Game",
    "short": "Rush TD/G",
    "unit": "offense",
    "phrase": "rushing offense",
    "mirror": "opponent_rushing_tds_per_game",
    "higherIsBetter": true
  },
  "opponent_rushing_tds_per_game": {
    "id": "opponent_rushing_tds_per_game",
    "label": "Opponent Rushing TDs Per Game",
    "short": "Opp Rush TD/G",
    "unit": "defense",
    "phrase": "run defense",
    "mirror": "rushing_tds_per_game",
    "higherIsBetter": false
  },
  "points_per_game": {
    "id": "points_per_game",
    "label": "Points Per Game",
    "short": "Pts/G",
    "unit": "offense",
    "phrase": "scoring offense",
    "mirror": "opponent_points_per_game",
    "higherIsBetter": true
  },
  "opponent_points_per_game": {
    "id": "opponent_points_per_game",
    "label": "Opponent Points Per Game",
    "short": "Opp Pts/G",
    "unit": "defense",
    "phrase": "scoring defense",
    "mirror": "points_per_game",
    "higherIsBetter": false
  },
  "q1_points_per_game": {
    "id": "q1_points_per_game",
    "label": "Q1 Points Per Game",
    "short": "Q1 Pts/G",
    "unit": "offense",
    "phrase": "first-quarter offense",
    "mirror": "opponent_q1_points_per_game",
    "higherIsBetter": true
  },
  "opponent_q1_points_per_game": {
    "id": "opponent_q1_points_per_game",
    "label": "Opponent Q1 Points Per Game",
    "short": "Opp Q1 Pts/G",
    "unit": "defense",
    "phrase": "first-quarter defense",
    "mirror": "q1_points_per_game",
    "higherIsBetter": false
  },
  "fg_made_per_game": {
    "id": "fg_made_per_game",
    "label": "FG Made Per Game",
    "short": "FG Made/G",
    "unit": "special",
    "phrase": "field goal unit",
    "mirror": "opponent_fg_attempts_per_game",
    "higherIsBetter": true
  },
  "opponent_fg_attempts_per_game": {
    "id": "opponent_fg_attempts_per_game",
    "label": "Opponent FG Attempts Per Game",
    "short": "Opp FG Att/G",
    "unit": "special",
    "phrase": "field goal defense",
    "mirror": "fg_made_per_game",
    "higherIsBetter": false
  },
  "interceptions_thrown_per_game": {
    "id": "interceptions_thrown_per_game",
    "label": "Interceptions Thrown Per Game",
    "short": "INT Thrown/G",
    "unit": "offense",
    "phrase": "ball security",
    "mirror": "opponent_interceptions_thrown_per_game",
    "higherIsBetter": false
  },
  "opponent_interceptions_thrown_per_game": {
    "id": "opponent_interceptions_thrown_per_game",
    "label": "Opponent Interceptions Thrown Per Game",
    "short": "INT Forced/G",
    "unit": "defense",
    "phrase": "takeaway defense",
    "mirror": "interceptions_thrown_per_game",
    "higherIsBetter": true
  },
  "sacks_per_game": {
    "id": "sacks_per_game",
    "label": "Sacks Per Game",
    "short": "Sacks/G",
    "unit": "defense",
    "phrase": "pass rush",
    "mirror": "opponent_sacks_per_game",
    "higherIsBetter": true
  },
  "opponent_sacks_per_game": {
    "id": "opponent_sacks_per_game",
    "label": "Opponent Sacks Per Game",
    "short": "Sacks Allowed/G",
    "unit": "offense",
    "phrase": "pass protection",
    "mirror": "sacks_per_game",
    "higherIsBetter": false
  },
  "defensive_tds_per_game": {
    "id": "defensive_tds_per_game",
    "label": "Defensive TDs Per Game",
    "short": "Def TD/G",
    "unit": "defense",
    "phrase": "defensive scoring",
    "mirror": "opponent_defensive_tds_per_game",
    "higherIsBetter": true
  },
  "opponent_defensive_tds_per_game": {
    "id": "opponent_defensive_tds_per_game",
    "label": "Opponent Defensive TDs Per Game",
    "short": "Def TD Allowed/G",
    "unit": "offense",
    "phrase": "turnover protection",
    "mirror": "defensive_tds_per_game",
    "higherIsBetter": false
  }
};

export const STAT_ORDER: string[] = [
  "passing_yards_per_game",
  "opponent_passing_yards_per_game",
  "passing_tds_per_game",
  "opponent_passing_tds_per_game",
  "rushing_yards_per_game",
  "opponent_rushing_yards_per_game",
  "rushing_tds_per_game",
  "opponent_rushing_tds_per_game",
  "points_per_game",
  "opponent_points_per_game",
  "q1_points_per_game",
  "opponent_q1_points_per_game",
  "fg_made_per_game",
  "opponent_fg_attempts_per_game",
  "interceptions_thrown_per_game",
  "opponent_interceptions_thrown_per_game",
  "sacks_per_game",
  "opponent_sacks_per_game",
  "defensive_tds_per_game",
  "opponent_defensive_tds_per_game"
];

export function mirror(id: string): string {
  return STATS[id].mirror;
}
