// Generated by `python -m props codegen`. Do not edit by hand.
// Source of truth: pipeline/props/{teams.py,config.py,markets.py}

export interface Team {
  id: string;
  location: string;
  nickname: string;
  name: string;
  short: string;
  conference: string;
  division: string;
  primary: string;
  secondary: string;
}

export const TEAMS: Record<string, Team> = {
  "ARI": {
    "id": "ARI",
    "location": "Arizona",
    "nickname": "Cardinals",
    "name": "Arizona Cardinals",
    "short": "Arizona",
    "conference": "NFC",
    "division": "NFC West",
    "primary": "#a40227",
    "secondary": "#ffffff"
  },
  "ATL": {
    "id": "ATL",
    "location": "Atlanta",
    "nickname": "Falcons",
    "name": "Atlanta Falcons",
    "short": "Atlanta",
    "conference": "NFC",
    "division": "NFC South",
    "primary": "#a71930",
    "secondary": "#000000"
  },
  "BAL": {
    "id": "BAL",
    "location": "Baltimore",
    "nickname": "Ravens",
    "name": "Baltimore Ravens",
    "short": "Baltimore",
    "conference": "AFC",
    "division": "AFC North",
    "primary": "#29126f",
    "secondary": "#000000"
  },
  "BUF": {
    "id": "BUF",
    "location": "Buffalo",
    "nickname": "Bills",
    "name": "Buffalo Bills",
    "short": "Buffalo",
    "conference": "AFC",
    "division": "AFC East",
    "primary": "#00338d",
    "secondary": "#d50a0a"
  },
  "CAR": {
    "id": "CAR",
    "location": "Carolina",
    "nickname": "Panthers",
    "name": "Carolina Panthers",
    "short": "Carolina",
    "conference": "NFC",
    "division": "NFC South",
    "primary": "#0085ca",
    "secondary": "#000000"
  },
  "CHI": {
    "id": "CHI",
    "location": "Chicago",
    "nickname": "Bears",
    "name": "Chicago Bears",
    "short": "Chicago",
    "conference": "NFC",
    "division": "NFC North",
    "primary": "#0b1c3a",
    "secondary": "#e64100"
  },
  "CIN": {
    "id": "CIN",
    "location": "Cincinnati",
    "nickname": "Bengals",
    "name": "Cincinnati Bengals",
    "short": "Cincinnati",
    "conference": "AFC",
    "division": "AFC North",
    "primary": "#fb4f14",
    "secondary": "#000000"
  },
  "CLE": {
    "id": "CLE",
    "location": "Cleveland",
    "nickname": "Browns",
    "name": "Cleveland Browns",
    "short": "Cleveland",
    "conference": "AFC",
    "division": "AFC North",
    "primary": "#472a08",
    "secondary": "#ff3c00"
  },
  "DAL": {
    "id": "DAL",
    "location": "Dallas",
    "nickname": "Cowboys",
    "name": "Dallas Cowboys",
    "short": "Dallas",
    "conference": "NFC",
    "division": "NFC East",
    "primary": "#002a5c",
    "secondary": "#b0b7bc"
  },
  "DEN": {
    "id": "DEN",
    "location": "Denver",
    "nickname": "Broncos",
    "name": "Denver Broncos",
    "short": "Denver",
    "conference": "AFC",
    "division": "AFC West",
    "primary": "#0a2343",
    "secondary": "#fc4c02"
  },
  "DET": {
    "id": "DET",
    "location": "Detroit",
    "nickname": "Lions",
    "name": "Detroit Lions",
    "short": "Detroit",
    "conference": "NFC",
    "division": "NFC North",
    "primary": "#0076b6",
    "secondary": "#bbbbbb"
  },
  "GB": {
    "id": "GB",
    "location": "Green Bay",
    "nickname": "Packers",
    "name": "Green Bay Packers",
    "short": "Green Bay",
    "conference": "NFC",
    "division": "NFC North",
    "primary": "#204e32",
    "secondary": "#ffb612"
  },
  "HOU": {
    "id": "HOU",
    "location": "Houston",
    "nickname": "Texans",
    "name": "Houston Texans",
    "short": "Houston",
    "conference": "AFC",
    "division": "AFC South",
    "primary": "#021018",
    "secondary": "#eb0028"
  },
  "IND": {
    "id": "IND",
    "location": "Indianapolis",
    "nickname": "Colts",
    "name": "Indianapolis Colts",
    "short": "Indianapolis",
    "conference": "AFC",
    "division": "AFC South",
    "primary": "#003b75",
    "secondary": "#ffffff"
  },
  "JAX": {
    "id": "JAX",
    "location": "Jacksonville",
    "nickname": "Jaguars",
    "name": "Jacksonville Jaguars",
    "short": "Jacksonville",
    "conference": "AFC",
    "division": "AFC South",
    "primary": "#007487",
    "secondary": "#d7a22a"
  },
  "KC": {
    "id": "KC",
    "location": "Kansas City",
    "nickname": "Chiefs",
    "name": "Kansas City Chiefs",
    "short": "Kansas City",
    "conference": "AFC",
    "division": "AFC West",
    "primary": "#e31837",
    "secondary": "#ffb612"
  },
  "LAC": {
    "id": "LAC",
    "location": "Los Angeles",
    "nickname": "Chargers",
    "name": "Los Angeles Chargers",
    "short": "LA Chargers",
    "conference": "AFC",
    "division": "AFC West",
    "primary": "#0080c6",
    "secondary": "#ffc20e"
  },
  "LAR": {
    "id": "LAR",
    "location": "Los Angeles",
    "nickname": "Rams",
    "name": "Los Angeles Rams",
    "short": "LA Rams",
    "conference": "NFC",
    "division": "NFC West",
    "primary": "#003594",
    "secondary": "#ffd100"
  },
  "LV": {
    "id": "LV",
    "location": "Las Vegas",
    "nickname": "Raiders",
    "name": "Las Vegas Raiders",
    "short": "Las Vegas",
    "conference": "AFC",
    "division": "AFC West",
    "primary": "#000000",
    "secondary": "#a5acaf"
  },
  "MIA": {
    "id": "MIA",
    "location": "Miami",
    "nickname": "Dolphins",
    "name": "Miami Dolphins",
    "short": "Miami",
    "conference": "AFC",
    "division": "AFC East",
    "primary": "#008e97",
    "secondary": "#fc4c02"
  },
  "MIN": {
    "id": "MIN",
    "location": "Minnesota",
    "nickname": "Vikings",
    "name": "Minnesota Vikings",
    "short": "Minnesota",
    "conference": "NFC",
    "division": "NFC North",
    "primary": "#4f2683",
    "secondary": "#ffc62f"
  },
  "NE": {
    "id": "NE",
    "location": "New England",
    "nickname": "Patriots",
    "name": "New England Patriots",
    "short": "New England",
    "conference": "AFC",
    "division": "AFC East",
    "primary": "#002a5c",
    "secondary": "#c60c30"
  },
  "NO": {
    "id": "NO",
    "location": "New Orleans",
    "nickname": "Saints",
    "name": "New Orleans Saints",
    "short": "New Orleans",
    "conference": "NFC",
    "division": "NFC South",
    "primary": "#d3bc8d",
    "secondary": "#000000"
  },
  "NYG": {
    "id": "NYG",
    "location": "New York",
    "nickname": "Giants",
    "name": "New York Giants",
    "short": "NY Giants",
    "conference": "NFC",
    "division": "NFC East",
    "primary": "#003c7f",
    "secondary": "#c9243f"
  },
  "NYJ": {
    "id": "NYJ",
    "location": "New York",
    "nickname": "Jets",
    "name": "New York Jets",
    "short": "NY Jets",
    "conference": "AFC",
    "division": "AFC East",
    "primary": "#115740",
    "secondary": "#ffffff"
  },
  "PHI": {
    "id": "PHI",
    "location": "Philadelphia",
    "nickname": "Eagles",
    "name": "Philadelphia Eagles",
    "short": "Philadelphia",
    "conference": "NFC",
    "division": "NFC East",
    "primary": "#06424d",
    "secondary": "#000000"
  },
  "PIT": {
    "id": "PIT",
    "location": "Pittsburgh",
    "nickname": "Steelers",
    "name": "Pittsburgh Steelers",
    "short": "Pittsburgh",
    "conference": "AFC",
    "division": "AFC North",
    "primary": "#000000",
    "secondary": "#ffb612"
  },
  "SEA": {
    "id": "SEA",
    "location": "Seattle",
    "nickname": "Seahawks",
    "name": "Seattle Seahawks",
    "short": "Seattle",
    "conference": "NFC",
    "division": "NFC West",
    "primary": "#002a5c",
    "secondary": "#69be28"
  },
  "SF": {
    "id": "SF",
    "location": "San Francisco",
    "nickname": "49ers",
    "name": "San Francisco 49ers",
    "short": "San Francisco",
    "conference": "NFC",
    "division": "NFC West",
    "primary": "#aa0000",
    "secondary": "#b3995d"
  },
  "TB": {
    "id": "TB",
    "location": "Tampa Bay",
    "nickname": "Buccaneers",
    "name": "Tampa Bay Buccaneers",
    "short": "Tampa Bay",
    "conference": "NFC",
    "division": "NFC South",
    "primary": "#bd1c36",
    "secondary": "#3e3a35"
  },
  "TEN": {
    "id": "TEN",
    "location": "Tennessee",
    "nickname": "Titans",
    "name": "Tennessee Titans",
    "short": "Tennessee",
    "conference": "AFC",
    "division": "AFC South",
    "primary": "#4495d2",
    "secondary": "#001532"
  },
  "WAS": {
    "id": "WAS",
    "location": "Washington",
    "nickname": "Commanders",
    "name": "Washington Commanders",
    "short": "Washington",
    "conference": "NFC",
    "division": "NFC East",
    "primary": "#5a1414",
    "secondary": "#ffb612"
  }
};

export const TEAM_IDS: string[] = ["ARI", "ATL", "BAL", "BUF", "CAR", "CHI", "CIN", "CLE", "DAL", "DEN", "DET", "GB", "HOU", "IND", "JAX", "KC", "LAC", "LAR", "LV", "MIA", "MIN", "NE", "NO", "NYG", "NYJ", "PHI", "PIT", "SEA", "SF", "TB", "TEN", "WAS"];

export function team(id: string): Team {
  return (
    TEAMS[id] ?? {
      id,
      location: id,
      nickname: '',
      name: id,
      short: id,
      conference: '',
      division: '',
      primary: '#666666',
      secondary: '#999999',
    }
  );
}
