"""Emit the app's domain constants from the Python definitions.

    python -m props codegen --ts app/src/domain

Team metadata, stat labels, the mirror map and the market list all exist once,
in Python, and are generated into TypeScript. CI fails if regenerating produces
a diff, so the two languages cannot drift.
"""

from __future__ import annotations

import json
import pathlib
from typing import Dict

from . import teams as registry
from .config import STATS, STAT_ORDER
from .markets import MARKETS, MARKET_ORDER

BANNER = (
    "// Generated by `python -m props codegen`. Do not edit by hand.\n"
    "// Source of truth: pipeline/props/{teams.py,config.py,markets.py}\n\n"
)


def teams_ts() -> str:
    entries: Dict[str, dict] = {}
    for team in registry.all_teams():
        entries[team.id] = {
            "id": team.id,
            "location": team.location,
            "nickname": team.nickname,
            "name": team.full_name,
            "short": team.tr_name,
            "conference": team.conference,
            "division": team.division,
            "primary": team.primary_color,
            "secondary": team.secondary_color,
        }
    return (
        BANNER
        + "export interface Team {\n"
        "  id: string;\n  location: string;\n  nickname: string;\n  name: string;\n"
        "  short: string;\n  conference: string;\n  division: string;\n"
        "  primary: string;\n  secondary: string;\n}\n\n"
        f"export const TEAMS: Record<string, Team> = {json.dumps(entries, indent=2)};\n\n"
        f"export const TEAM_IDS: string[] = {json.dumps(list(registry.TEAM_IDS))};\n\n"
        "export function team(id: string): Team {\n"
        "  return (\n    TEAMS[id] ?? {\n"
        "      id,\n      location: id,\n      nickname: '',\n      name: id,\n"
        "      short: id,\n      conference: '',\n      division: '',\n"
        "      primary: '#666666',\n      secondary: '#999999',\n    }\n  );\n}\n"
    )


def stats_ts() -> str:
    entries = {
        stat_id: {
            "id": STATS[stat_id].id,
            "label": STATS[stat_id].label,
            "short": STATS[stat_id].short,
            "unit": STATS[stat_id].unit,
            "phrase": STATS[stat_id].phrase,
            "mirror": STATS[stat_id].mirror,
            "higherIsBetter": STATS[stat_id].higher_is_better,
        }
        for stat_id in STAT_ORDER
    }
    return (
        BANNER
        + "export interface StatDef {\n"
        "  id: string;\n  label: string;\n  short: string;\n"
        "  unit: 'offense' | 'defense' | 'special';\n  phrase: string;\n"
        "  mirror: string;\n  higherIsBetter: boolean;\n}\n\n"
        f"export const STATS: Record<string, StatDef> = {json.dumps(entries, indent=2)};\n\n"
        f"export const STAT_ORDER: string[] = {json.dumps(list(STAT_ORDER), indent=2)};\n\n"
        "export function mirror(id: string): string {\n"
        "  return STATS[id].mirror;\n}\n"
    )


def markets_ts() -> str:
    entries = {
        market_id: {
            "id": MARKETS[market_id].id,
            "label": MARKETS[market_id].label,
            "position": MARKETS[market_id].position,
            "unit": MARKETS[market_id].unit,
            "noun": MARKETS[market_id].noun,
        }
        for market_id in MARKET_ORDER
    }
    return (
        BANNER
        + "export interface MarketDef {\n"
        "  id: string;\n  label: string;\n  position: string;\n"
        "  unit: string;\n  noun: string;\n}\n\n"
        f"export const MARKETS: Record<string, MarketDef> = {json.dumps(entries, indent=2)};\n\n"
        f"export const MARKET_ORDER: string[] = {json.dumps(list(MARKET_ORDER), indent=2)};\n\n"
        "export const POSITIONS = ['QB', 'RB', 'WR', 'TE'] as const;\n"
    )


def write(target: str) -> Dict[str, bool]:
    directory = pathlib.Path(target)
    directory.mkdir(parents=True, exist_ok=True)
    written = {}
    for name, body in (
        ("teams.ts", teams_ts()),
        ("stats.ts", stats_ts()),
        ("markets.ts", markets_ts()),
    ):
        path = directory / name
        existing = path.read_text() if path.exists() else None
        if existing != body:
            path.write_text(body)
        written[name] = existing != body
    return written
